### ISSUE TITLE
Un'goro cards missing from export

### ISSUE THREAD

**Issue by brokkr** [pawl/HearthstoneCollectionExporter#2]
Just did an export today (26th of April). AFAICT no cards from the Un'Goro set appear in in the csv file. I have checked a few specific ones - Tar Creeper, Lyra Sunshard, Hemet Jungle Hunter - and that the set does not appear in the 'Set' column.

**Comment by pawl** [comment]
Fixed by: https://github.com/pawl/HearthstoneCollectionExporter/pull/3
